//! The embedded doc corpus and per-file overrides.
//!
//! The `languages/` principle/metric Markdown is compiled into the binary (see
//! `build.rs`), so the tool can serve a doc's text directly (`docs HK`)
//! without a network fetch. A project may substitute any one fragment via
//! `[templates.languages.<lang>.<ID>]` (read from disk instead of the embedded
//! copy) — the doc analogue of overriding a config key.

use crate::config::TemplatesConfig;
use anyhow::{Context, Result};
use code_ranker_plugin_api::{Principle, level::AttributeSpec};
use std::collections::BTreeMap;

// `CORPUS: &[(&str, &str)]` — `(<lang>/<ID>.md, contents)` — generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/corpus.rs"));

/// The embedded contents of a corpus doc by its `<lang>/<ID>.md` relative path.
fn corpus_doc(rel: &str) -> Option<&'static str> {
    CORPUS.iter().find(|(k, _)| *k == rel).map(|(_, v)| *v)
}

/// Normalize an id / subject for matching: lowercase, keep only ASCII
/// alphanumerics — so `fan_in`, `Fan-in`, and `FAN in` all collapse to `fanin`.
/// The single rule every `docs`-subject and doc-id lookup matches through, so a
/// metric / principle / doc resolves regardless of separators or case.
pub(crate) fn normalize_id(s: &str) -> String {
    s.chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .map(|c| c.to_ascii_lowercase())
        .collect()
}

/// The base-corpus doc stem a metric key maps to, matched on the normalized form
/// (so `hk`→`HK`, `fan_in`→`Fan-in`). `None` when the metric ships no prose doc
/// (e.g. `sloc`, `eta1`). Replaces the old "parse the doc id out of the metric's
/// remediation prose" — the mapping is the corpus itself, not a stored string.
pub(crate) fn metric_doc_stem(key: &str) -> Option<&'static str> {
    let want = normalize_id(key);
    CORPUS.iter().find_map(|(rel, _)| {
        let stem = rel.strip_prefix("base/")?.strip_suffix(".md")?;
        (normalize_id(stem) == want).then_some(stem)
    })
}

/// The corpus path a doc id resolves to, as `<lang>/<ID>.md`. In order: a matching
/// principle's already-resolved `doc_url`; a metric key whose corpus doc is found by
/// [`metric_doc_stem`] (honoring a language's `<lang>/` override); else any base doc
/// addressable by its (normalized) filename stem. All matching is separator- and
/// case-insensitive (see [`normalize_id`]).
fn doc_rel_path(
    principles: &[Principle],
    node_attributes: &BTreeMap<String, AttributeSpec>,
    id: &str,
) -> Option<String> {
    // `cycle` is the ADP principle's metric lens (not a real node attribute), so
    // its doc IS the ADP doc — resolve it through the ADP principle below.
    let id = if normalize_id(id) == "cycle" {
        "ADP"
    } else {
        id
    };
    // Principle (normalized id, e.g. `SRP`, `adp`).
    if let Some(p) = principles
        .iter()
        .find(|p| normalize_id(&p.id) == normalize_id(id))
        && let Some(url) = &p.doc_url
        && let Some(rel) = url_tail(url)
    {
        return Some(rel);
    }
    // Metric doc: a node attribute whose key maps to a corpus doc (`hk`→`HK`,
    // `fan_in`→`Fan-in`). Metric docs default to the neutral `base/` corpus but
    // honor a language's doc override exactly as principle docs do — if the plugin
    // routes its principle docs to a `<lang>/` folder and ships a `<lang>/<doc>.md`,
    // serve that; otherwise the shared `base/`.
    let key = id.to_ascii_lowercase();
    if node_attributes.contains_key(&key)
        && let Some(stem) = metric_doc_stem(&key)
    {
        let lang_doc = override_lang(principles)
            .map(|lang| format!("{lang}/{stem}.md"))
            .filter(|rel| corpus_doc(rel).is_some());
        return Some(lang_doc.unwrap_or_else(|| format!("base/{stem}.md")));
    }
    // Fallback: any base corpus doc addressable by its filename stem (normalized) —
    // covers docs that are neither a principle nor a metric: `Fan-in` / `Fan-out`
    // (key is `fan_in`, not the hyphenated filename), the `metrics` reference, and
    // the `AI` overview index.
    let want = normalize_id(id);
    CORPUS.iter().find_map(|(rel, _)| {
        let stem = rel.strip_prefix("base/")?.strip_suffix(".md")?;
        (normalize_id(stem) == want).then(|| (*rel).to_string())
    })
}

/// Extract the `<lang>/<ID>.md` tail of a corpus URL (`…/plugins/base/HK.md`
/// → `base/HK.md`). A `remediation` value is free prose ending in the URL, so the
/// match is anchored on the `/plugins/` segment, not the string start.
fn url_tail(url: &str) -> Option<String> {
    let after = url.rsplit_once("/plugins/")?.1;
    // Stop at whitespace in case the URL is embedded in a sentence.
    Some(after.split_whitespace().next()?.to_string())
}

/// The corpus folder a plugin's overridden docs resolve to (e.g. `rust`), inferred
/// from the principle `doc_url`s the config already routed through `doc_overrides`;
/// `None` when the plugin uses the shared `base/` corpus. Lets metric docs reuse the
/// same override decision without re-reading the plugin config here.
fn override_lang(principles: &[Principle]) -> Option<String> {
    principles
        .iter()
        .filter_map(|p| p.doc_url.as_deref())
        .filter_map(url_tail)
        .filter_map(|rel| rel.split_once('/').map(|(l, _)| l.to_string()))
        .find(|l| l != "base")
}

/// A language doc is a **manifest** (assembled from the base) when it carries at
/// least one `<!-- doc:base … -->` include; a full standalone doc has none and is
/// served verbatim. (A manifest may still write its own `# ` H1 + TL;DR head.)
fn is_manifest(md: &str) -> bool {
    md.contains("<!-- doc:base")
}

/// Marker placed in `base/AI.md`; expands to a one-paragraph summary of every
/// other base doc (its `**TL;DR**` paragraph, or the first prose paragraph when a
/// doc has none), so the AI overview always lists the current catalog.
const TLDR_INDEX_MARKER: &str = "<!-- doc:tldr-index -->";

/// Markers bracketing the `base/AI.md` *Select a language* section — the plugin-setup
/// template (with `{reason}` / `{plugins}` / `{config_version}` placeholders filled by
/// the `ai` command, see `ai::fill_select`). The `ai` command shows it (the intro,
/// [`ai_doc_intro`]) only when no plugin resolves; every other served doc strips the
/// whole section ([`expand_tldr_index`]) so its template never reaches the terminal.
const AI_SELECT_START: &str = "<!-- ai:select-start -->";
const AI_SELECT_END: &str = "<!-- ai:select-end -->";

/// A doc or prompt printed to stdout must end in exactly one trailing newline so
/// the shell prompt resumes on its own line. Returns `md` with a newline ensured.
/// Shared by the `docs` stdout paths so the rule lives in one
/// (unit-testable) place rather than being re-implemented at each call site.
pub(crate) fn with_trailing_newline(mut md: String) -> String {
    if !md.ends_with('\n') {
        md.push('\n');
    }
    md
}

/// One catalog entry on a SINGLE line: a `### <title>` heading plus the
/// language-scoped `docs <lang> <stem>` pointer to the full doc. Deliberately
/// compact (no TL;DR summary) so the AI playbook's catalog stays scannable —
/// one line per principle / metric.
fn catalog_entry(title: &str, lang: &str, stem: &str) -> String {
    format!("### {title} Full doc: `code-ranker docs {lang} {stem}`")
}

/// Build the catalog the `<!-- doc:tldr-index -->` marker expands to: every
/// `base/<ID>.md` (except `AI.md` itself), alphabetical, one line each (see
/// [`catalog_entry`]). `lang` is the resolved plugin so every pointer reads
/// `code-ranker docs <lang> <ID>` (docs are per-language).
fn tldr_index(lang: &str) -> String {
    let mut entries: Vec<(String, String)> = CORPUS
        .iter()
        .filter_map(|(rel, contents)| {
            let stem = rel.strip_prefix("base/")?.strip_suffix(".md")?;
            if stem.eq_ignore_ascii_case("AI") {
                return None;
            }
            let title = contents
                .lines()
                .find_map(|l| l.strip_prefix("# "))
                .unwrap_or(stem)
                .trim();
            let entry = catalog_entry(title, lang, stem);
            Some((stem.to_ascii_lowercase(), entry))
        })
        .collect();
    entries.sort_by(|a, b| a.0.cmp(&b.0));
    entries
        .into_iter()
        .map(|(_, e)| e)
        .collect::<Vec<_>>()
        .join("\n")
}

/// Replace a `<!-- doc:tldr-index -->` marker with the generated catalog; a no-op
/// for docs that don't carry it. Also drops the `base/AI.md` *Select a language*
/// section ([`strip_select_section`]) — it is the `ai` command's unresolved-only
/// template and must never appear in a served doc (`docs <lang> AI`, `ai` when resolved).
fn expand_tldr_index(md: &str, lang: &str) -> String {
    let md = strip_select_section(md);
    if md.contains(TLDR_INDEX_MARKER) {
        md.replace(TLDR_INDEX_MARKER, &tldr_index(lang))
    } else {
        md
    }
}

/// Remove the `<!-- ai:select-start -->`…`<!-- ai:select-end -->` block (inclusive),
/// rejoining the surrounding text with a blank line. A no-op for docs without it.
fn strip_select_section(md: &str) -> String {
    match (md.find(AI_SELECT_START), md.find(AI_SELECT_END)) {
        (Some(start), Some(end)) if start < end => {
            let after = &md[end + AI_SELECT_END.len()..];
            format!("{}\n\n{}", md[..start].trim_end(), after.trim_start())
        }
        _ => md.to_string(),
    }
}

/// Resolve a doc from the principle + metric specs directly — no snapshot, no
/// analysis. Backs the `docs <principle>` / `docs <metric>` paths, where the specs
/// are built from the merged config and the resolved plugin rather than from an
/// analyzed project.
pub(crate) fn resolve_doc_from_specs(
    principles: &[Principle],
    node_attributes: &BTreeMap<String, AttributeSpec>,
    templates: &TemplatesConfig,
    id: &str,
) -> Result<String> {
    // The tldr-index marker only ever lives in `base/AI.md` (served via `ai_doc`),
    // so a single-doc resolution never actually expands it; `base` is an inert
    // fallback language for the (unreachable here) marker case.
    Ok(expand_tldr_index(
        &resolve_doc_raw(principles, node_attributes, templates, id)?,
        "base",
    ))
}

/// The offline AI-agent overview (`base/AI.md`) with its catalog index expanded —
/// served straight from the embedded corpus with **no snapshot, no project
/// analysis, and no plugin detection**. Backs the `docs ai` subcommand, so the
/// playbook prints in any directory regardless of language markers.
pub(crate) fn ai_doc(lang: &str) -> Result<String> {
    let md = corpus_doc("base/AI.md").context("base/AI.md is not embedded in this build")?;
    Ok(expand_tldr_index(md, lang))
}

/// The brief intro from `base/AI.md` for the `ai` command's unresolved mode:
/// everything up to and including the *Select a language* section (its placeholders
/// still raw — `ai::fill_select` fills them). That is the product description, the
/// command list, and the plugin-setup template; the analysis playbook + catalog after
/// it stay withheld until a language is chosen.
#[allow(dead_code)] // exercised by tests; the `ai` command now requires a language.
pub(crate) fn ai_doc_intro() -> Result<String> {
    let md = corpus_doc("base/AI.md").context("base/AI.md is not embedded in this build")?;
    let head = md.split(AI_SELECT_END).next().unwrap_or(md);
    Ok(format!(
        "{}\n",
        head.replace(&format!("{AI_SELECT_START}\n"), "").trim()
    ))
}

/// Resolve the Markdown for doc `id` against the active snapshot. In order:
/// 1. a `[templates.languages.<lang>.<ID>]` override → that file verbatim (the
///    user supplies the final doc, "as if it were `languages/<lang>/<ID>.md`");
/// 2. a language **manifest** (`<lang>/<ID>.md` with `<!-- doc:base … -->` includes)
///    → assembled from `base/<ID>.md` by [`crate::compose::compose`];
/// 3. the embedded `<lang>/<ID>.md` (a full standalone doc); else the `base/<ID>.md`
///    fallback.
///
/// `id` is a principle id (`SRP`) or a metric key (`hk`).
fn resolve_doc_raw(
    principles: &[Principle],
    node_attributes: &BTreeMap<String, AttributeSpec>,
    templates: &TemplatesConfig,
    id: &str,
) -> Result<String> {
    let rel = doc_rel_path(principles, node_attributes, id).with_context(|| {
        let known: Vec<&str> = principles.iter().map(|p| p.id.as_str()).collect();
        format!(
            "no principle or metric doc for {id:?}. Known principles: {}",
            known.join(", ")
        )
    })?;
    let (lang, file) = rel.split_once('/').unwrap_or(("base", &rel));
    let stem = file.strip_suffix(".md").unwrap_or(file);

    // 1. Override wins: the user's file is the final doc — no composition.
    if let Some(path) = templates.languages.get(lang).and_then(|m| m.get(stem)) {
        return std::fs::read_to_string(path)
            .with_context(|| format!("reading template override {path} for {lang}/{stem}"));
    }

    // 2. A language manifest → assemble it from the neutral base sections. A
    //    `templates.languages.base.<ID>` override substitutes the base here too, so
    //    it flows through into every language that assembles over it.
    if lang != "base"
        && let Some(manifest) = corpus_doc(&rel)
        && is_manifest(manifest)
    {
        let base = match templates.languages.get("base").and_then(|m| m.get(stem)) {
            Some(path) => std::fs::read_to_string(path)
                .with_context(|| format!("reading base template override {path} for {stem}"))?,
            None => corpus_doc(&format!("base/{stem}.md"))
                .with_context(|| format!("manifest {rel} has no base/{stem}.md"))?
                .to_string(),
        };
        return crate::compose::compose(manifest, &base, lang_display(lang));
    }

    // 3. The embedded full doc, else the base fallback.
    corpus_doc(&rel)
        .map(str::to_string)
        .or_else(|| corpus_doc(&format!("base/{stem}.md")).map(str::to_string))
        .with_context(|| format!("doc {rel} is not embedded in this build"))
}

/// Display name for a corpus language folder, used as the H1 `(in <Lang>)` suffix.
fn lang_display(lang: &str) -> &str {
    match lang {
        "rust" => "Rust",
        "python" => "Python",
        "ts" => "TypeScript",
        "js" => "JavaScript",
        "go" => "Go",
        "c" => "C",
        "cpp" => "C++",
        "csharp" => "C#",
        "md" => "Markdown",
        other => other,
    }
}

#[cfg(test)]
#[path = "templates_test.rs"]
mod tests;
