//! The embedded doc corpus and per-file overrides.
//!
//! The `languages/` principle/metric Markdown is compiled into the binary (see
//! `build.rs`), so the tool can serve a doc's text directly (`report --doc HK`)
//! without a network fetch. A project may substitute any one fragment via
//! `[templates.languages.<lang>.<ID>]` (read from disk instead of the embedded
//! copy) — the doc analogue of overriding a config key.

use crate::config::TemplatesConfig;
use anyhow::{Context, Result};
use code_ranker_graph::snapshot::Snapshot;

// `CORPUS: &[(&str, &str)]` — `(<lang>/<ID>.md, contents)` — generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/corpus.rs"));

/// The embedded contents of a corpus doc by its `<lang>/<ID>.md` relative path.
fn corpus_doc(rel: &str) -> Option<&'static str> {
    CORPUS.iter().find(|(k, _)| *k == rel).map(|(_, v)| *v)
}

/// The corpus path a doc id resolves to, as `<lang>/<ID>.md` — read from the
/// already-resolved `doc_url` of a matching preset (principle docs) or the
/// `remediation` URL of a matching metric (coupling/complexity docs). Both encode
/// the post-fallback corpus location (own `<lang>/` or the shared `base/`), so the
/// override key namespace lines up with where the doc actually lives.
fn doc_rel_path(snap: &Snapshot, id: &str) -> Option<String> {
    // Principle preset (case-insensitive id, e.g. `SRP`, `adp`).
    if let Some(p) = snap.presets.iter().find(|p| p.id.eq_ignore_ascii_case(id))
        && let Some(url) = &p.doc_url
        && let Some(rel) = url_tail(url)
    {
        return Some(rel);
    }
    // Metric doc (attribute key is lowercase, e.g. `hk`, `cyclomatic`).
    let key = id.to_ascii_lowercase();
    let files = snap.graphs.get("files")?;
    let spec = files.node_attributes.get(&key)?;
    let rem = spec.remediation.as_ref()?;
    url_tail(rem)
}

/// Extract the `<lang>/<ID>.md` tail of a corpus URL (`…/languages/base/HK.md`
/// → `base/HK.md`). A `remediation` value is free prose ending in the URL, so the
/// match is anchored on the `/languages/` segment, not the string start.
fn url_tail(url: &str) -> Option<String> {
    let after = url.rsplit_once("/languages/")?.1;
    // Stop at whitespace in case the URL is embedded in a sentence.
    Some(after.split_whitespace().next()?.to_string())
}

/// A language doc is a **manifest** (assembled from the base) when it carries at
/// least one `<!-- doc:base … -->` include; a full standalone doc has none and is
/// served verbatim. (A manifest may still write its own `# ` H1 + TL;DR head.)
fn is_manifest(md: &str) -> bool {
    md.contains("<!-- doc:base")
}

/// Resolve the Markdown for doc `id` against the active snapshot. In order:
/// 1. a `[templates.languages.<lang>.<ID>]` override → that file verbatim (the
///    user supplies the final doc, "as if it were `languages/<lang>/<ID>.md`");
/// 2. a language **manifest** (`<lang>/<ID>.md` with `<!-- doc:base … -->` includes)
///    → assembled from `base/<ID>.md` by [`crate::compose::compose`];
/// 3. the embedded `<lang>/<ID>.md` (a full standalone doc); else the `base/<ID>.md`
///    fallback.
///
/// `id` is a preset id (`SRP`) or a metric key (`hk`).
pub(crate) fn resolve_doc(
    snap: &Snapshot,
    templates: &TemplatesConfig,
    id: &str,
) -> Result<String> {
    let rel = doc_rel_path(snap, id).with_context(|| {
        let known: Vec<&str> = snap.presets.iter().map(|p| p.id.as_str()).collect();
        format!(
            "no principle or metric doc for {id:?}. Known principles: {}",
            known.join(", ")
        )
    })?;
    let (lang, file) = rel.split_once('/').unwrap_or(("base", &rel));
    let stem = file.strip_suffix(".md").unwrap_or(file);

    // 1. Override wins: the user's file is the final doc — no composition.
    if let Some(path) = templates.languages.get(lang).and_then(|m| m.get(stem)) {
        return std::fs::read_to_string(path)
            .with_context(|| format!("reading template override {path} for {lang}/{stem}"));
    }

    // 2. A language manifest → assemble it from the neutral base sections. A
    //    `templates.languages.base.<ID>` override substitutes the base here too, so
    //    it flows through into every language that assembles over it.
    if lang != "base"
        && let Some(manifest) = corpus_doc(&rel)
        && is_manifest(manifest)
    {
        let base = match templates.languages.get("base").and_then(|m| m.get(stem)) {
            Some(path) => std::fs::read_to_string(path)
                .with_context(|| format!("reading base template override {path} for {stem}"))?,
            None => corpus_doc(&format!("base/{stem}.md"))
                .with_context(|| format!("manifest {rel} has no base/{stem}.md"))?
                .to_string(),
        };
        return crate::compose::compose(manifest, &base, lang_display(lang));
    }

    // 3. The embedded full doc, else the base fallback.
    corpus_doc(&rel)
        .map(str::to_string)
        .or_else(|| corpus_doc(&format!("base/{stem}.md")).map(str::to_string))
        .with_context(|| format!("doc {rel} is not embedded in this build"))
}

/// Write the published doc corpus into `out_dir` for GitHub Pages: every
/// `base/<ID>.md` copied as-is (the fallback corpus), every language **manifest**
/// (a `<lang>/<ID>.md` carrying `<!-- doc:base … -->` includes) emitted as its
/// assembled doc, and any full `<lang>/<ID>.md` copied through verbatim. Returns the
/// file count.
pub(crate) fn build_corpus(out_dir: &std::path::Path) -> Result<usize> {
    let mut written = 0usize;
    for (rel, contents) in CORPUS {
        let (lang, file) = match rel.split_once('/') {
            Some(p) => p,
            None => continue,
        };
        let stem = file.strip_suffix(".md").unwrap_or(file);

        let body: String = if lang != "base" && is_manifest(contents) {
            // Assemble: the published `<lang>/<ID>.md` is the manifest over base.
            let base = corpus_doc(&format!("base/{stem}.md"))
                .with_context(|| format!("manifest {rel} has no base/{stem}.md"))?;
            crate::compose::compose(contents, base, lang_display(lang))?
        } else {
            // `base/*` and full language docs are published verbatim.
            contents.to_string()
        };

        let dest = out_dir.join(rel);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
        std::fs::write(&dest, &body).with_context(|| format!("writing {}", dest.display()))?;
        written += 1;
    }
    Ok(written)
}

/// Display name for a corpus language folder, used as the H1 `(in <Lang>)` suffix.
fn lang_display(lang: &str) -> &str {
    match lang {
        "rust" => "Rust",
        "python" => "Python",
        "typescript" => "TypeScript",
        "javascript" => "JavaScript",
        "go" => "Go",
        "c" => "C",
        "cpp" => "C++",
        "csharp" => "C#",
        "markdown" => "Markdown",
        other => other,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn corpus_is_embedded_and_keyed_by_rel_path() {
        // The base fallback corpus is always present.
        assert!(corpus_doc("base/HK.md").is_some(), "base/HK.md embedded");
        assert!(corpus_doc("base/SRP.md").is_some(), "base/SRP.md embedded");
        assert!(corpus_doc("nope/X.md").is_none());
    }

    #[test]
    fn url_tail_extracts_corpus_path() {
        assert_eq!(
            url_tail("https://x/blob/main/languages/base/HK.md").as_deref(),
            Some("base/HK.md")
        );
        assert_eq!(
            url_tail("Download from https://x/main/languages/rust/SRP.md now").as_deref(),
            Some("rust/SRP.md"),
            "anchored on /languages/, trailing prose trimmed"
        );
        assert_eq!(url_tail("https://x/elsewhere/HK.md"), None);
    }

    #[test]
    fn bare_relative_path_defaults_to_base_folder() {
        // `split_once('/')` fallback: a path with no slash is treated as base/<id>.
        let (lang, file) = "HK.md".split_once('/').unwrap_or(("base", "HK.md"));
        assert_eq!((lang, file), ("base", "HK.md"));
    }
}
